export const CHANGE_PAGE_TO_SETTINGS = "CHANGE_PAGE_TO_SETTINGS";
export const CHANGE_PAGE_TO_DASHBOARD = "CHANGE_PAGE_TO_DASHBOARD";
export const SETTINGS_PAGE = "SETTINGS_PAGE";
export const DASHBOARD_PAGE = "DASHBOARD_PAGE";
export const CONFIRM_FAVOURITES = "CONFIRM_FAVOURITES";

//request coins
export const REQUEST_COINS_PENDING = "REQUEST_COINS_PENDING";
export const REQUEST_COINS_SUCCESS = "REQUEST_COINS_SUCCESS";
export const REQUEST_COINS_FAILED = "REQUEST_COINS_FAILED";

